# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Bikash R. Dinda / Cosmology Research"
title_separator          : "-"
name                     : &name "Bikash Ranjan Dinda"
description              : &description "Postdoctoral researcher in cosmology, specializing in dark energy and machine learning in astrophysics"
url                      : https://bikash-r-dinda.github.io
baseurl                  : ""
repository               : "bikash-r-dinda/bikash-r-dinda.github.io"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Bikash R. Dinda"
  pronouns         : "he/him"
  bio              : "Postdoctoral researcher at the University of the Western Cape. My work explores late-time cosmology, dark energy, and machine learning applications in astrophysics."
  location         : "Cape Town, South Africa"
  employer         : "University of the Western Cape"
  uri              : "https://bikash-r-dinda.github.io"
  email            : "bikashd18@gmail.com"

  academia         : 
  arxiv            : "https://arxiv.org/search/astro-ph?searchtype=author&query=Dinda%2C+B+R"
  googlescholar    : "https://scholar.google.com/citations?user=Ks5UD7QAAAAJ&hl=en"
  inspire-hep      : 
  impactstory      : 
  orcid            : "http://orcid.org/0000-0001-5432-667X"
  semantic         : 
  pubmed           : 
  researchgate     : "https://www.researchgate.net/profile/Bikash-Dinda-2"
  scopus           : 

  bitbucket        : 
  codepen          : 
  dribbble         : 
  github           : "bikash-r-dinda"
  kaggle           : 
  stackoverflow    : 

  artstation       : 
  bluesky          : 
  facebook         : 
  flickr           : 
  foursquare       : 
  goodreads        : 
  google_plus      : 
  keybase          : 
  instagram        : 
  lastfm           : 
  linkedin         : "bikash-r-dinda"
  mastodon         : 
  medium           : 
  pinterest        : 
  soundcloud       : 
  steam            : 
  telegram         : 
  tumblr           : 
  twitter          : "bikash_cosmo"
  vine             : 
  weibo            : 
  wikipedia        : 
  xing             : 
  youtube          : 
  zhihu            : 
  

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Africa/Johannesburg # https://en.wikipedia.org/wiki/South_Africa_Standard_Time


# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
