# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default" # Currently available options are "default", "air"
title                    : "Bikash R. Dinda / Cosmology Research"
title_separator          : "-"
name                     : &name "Bikash Ranjan Dinda"
description              : &description "Postdoc at UWC"
url                      : https://bikash-r-dinda.github.io
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "bikash-r-dinda/bikash-r-dinda.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Bikash Ranjan Dinda"
  pronouns         : "Ph.D."
  #bio              : "Postdoc at UWC"
  location         : "Cape Town, South Africa"
  employer         : "University of the Western Cape"
  uri              : "https://bikash-r-dinda.github.io"
  email            : "bikashd18@gmail.com" 

  # Academic websites
  academia         : 
  arxiv            : "https://arxiv.org/search/astro-ph?searchtype=author&query=Dinda%2C+B+R"
  googlescholar    : "https://scholar.google.com/citations?user=Ks5UD7QAAAAJ&hl=en"
  inspire-hep      : "https://inspirehep.net/authors/1467904"
  impactstory      : 
  orcid            : "http://orcid.org/0000-0001-5432-667X"
  semantic         : "https://www.semanticscholar.org/author/Bikash-Ranjan-Dinda/88616422"
  pubmed           : 
  researchgate     : "https://www.researchgate.net/profile/Bikash-Dinda-2"
  scopus           : "https://www.scopus.com/authid/detail.uri?authorId=56395161900"

  # Repositories and software development
  bitbucket        : 
  codepen          : 
  dribbble         : 
  github           : "bikash-r-dinda"
  kaggle           : 
  stackoverflow    : 

  # Social media
  artstation       : 
  bluesky          : 
  facebook         : 
  flickr           : 
  foursquare       : 
  goodreads        : 
  google_plus      : 
  keybase          : 
  instagram        : 
  lastfm           : 
  linkedin         : 
  mastodon         : 
  medium           : 
  pinterest        : 
  soundcloud       : 
  steam            : 
  telegram         : 
  tumblr           : 
  twitter          : 
  vine             : 
  weibo            : 
  wikipedia        : 
  xing             : 
  youtube          : 
  zhihu            : 

# Publication Category - The following the list of publication categories and their headings
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : false
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false      #change to true to add link to talkmap on talks page
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : 
  facebook:
    appid                :
    num_posts            : 
    colorscheme          : 
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" 
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"
atom_feed:
  hide                   : false     
  path                   : 

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : 
  username               :
  app_id                 :
  publisher              :
og_image                 :  
og_description           :  
social:
  type                   : Person
  name                   : Bikash R. Dinda
  links: 
    - https://inspirehep.net/authors/1467904
    - https://www.scopus.com/authid/detail.uri?authorId=56395161900
    - https://scholar.google.com/citations?user=Ks5UD7QAAAAJ&hl=en
    - https://orcid.org/0000-0001-5432-667X
    - https://arxiv.org/search/astro-ph?searchtype=author&query=Dinda%2C+B+R
    - https://www.researchgate.net/profile/Bikash-Dinda-2
    - https://github.com/bikash-r-dinda
    - https://www.semanticscholar.org/author/Bikash-Ranjan-Dinda/88616422
    - https://www.webofscience.com/wos/author/record/71760083
# Analytics
analytics:
  provider               : "false"
  google:
    tracking_id          :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# These settings control the types of collections used by the template
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  peer_review:
    output: true
    permalink: /:collection/:path/
  conference:
    output: true
    permalink: /:collection/:path/

# These settings control how pages and collections are included in the site
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed 

# Outputting
permalink: /:categories/:title/
# paginate: 5
# paginate_path: /page:num/
timezone: Africa/Johannesburg # matches South Africa time

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
